import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css'
import NavbarTab from '../components/Navbar'
import Display from '../components/Display'

export default function Home() {
  return (
    <div className='container bg'>
      <Head>
        <title>Going Green</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <NavbarTab /> */}
      <Display />
    </div>
  )
}
